from app.assets.ServerGroup import ServerGroupList, ServerGroupAdd, ServerGroupUpdate, ServerGroupDel
from app.assets.SysUser import SysUserList, SysUserAdd, SysUserUpdate, SysUserDel
from app.assets.ServerManagement import ServerAdd, ServerList, ServerCmd, ServerListCmd, ServerDel, GroupCmd, \
    GroupList, ServerUpdate, ServerScript
from app.api import route  # REV38-M1: 统一 ROUTES schema

ROUTES = [
    # ---- 资产组（管理仅 admin，查看所有用户）----
    route('/server/host/group/list', ServerGroupList, 'group_list',
          roles=['admin'],
          description='主机组分页列表'),
    route('/server/host/group/name_list', ServerGroupList, 'group_name_list',
          description='主机组名称列表（按权限过滤）'),
    route('/server/host/group/list_all', ServerGroupList, 'group_list_all',
          description='主机组完整列表'),
    route('/server/host/group/add', ServerGroupAdd, 'host_add',
          roles=['admin'],
          description='新增主机组'),
    route('/server/host/group/update', ServerGroupUpdate, 'update',
          roles=['admin'],
          description='更新主机组'),
    route('/server/host/group/del', ServerGroupDel, 'host_del',
          roles=['admin'],
          description='删除主机组'),

    # ---- 系统用户（管理仅 admin，name_list 所有用户按权限过滤）----
    route('/server/sys/user/list', SysUserList, 'sys_user_list',
          roles=['admin'],
          description='系统用户分页列表'),
    route('/server/sys/user/name_list', SysUserList, 'sys_user_name_list',
          description='系统用户名称列表（按权限过滤）'),
    route('/server/sys/user/list_all', SysUserList, 'sys_user_list_all',
          roles=['admin'],
          description='系统用户完整列表'),
    route('/server/sys/user/add', SysUserAdd, 'host_add',
          roles=['admin'],
          description='新增系统用户（SSH 凭据）'),
    route('/server/sys/user/update', SysUserUpdate, 'update',
          roles=['admin'],
          description='更新系统用户'),
    route('/server/sys/user/del', SysUserDel, 'host_del',
          roles=['admin'],
          description='删除系统用户'),

    # ---- 资产主机（管理仅 admin，操作/查看按权限过滤）----
    route('/server/host/add', ServerAdd, 'host_add',
          roles=['admin'],
          description='新增主机资产'),
    route('/server/host/update', ServerUpdate, 'update',
          roles=['admin'],
          description='更新主机资产'),
    route('/server/host/del', ServerDel, 'host_del',
          roles=['admin'],
          description='删除主机资产'),
    route('/server/host/cmd', ServerCmd, 'sh_cmd',
          description='远程执行 SSH 命令（含 IP/UA 审计，REV37-H1）'),
    route('/server/host/list_all', ServerList, 'server_list_all',
          description='主机完整列表'),
    route('/server/host/list', ServerList, 'server_list',
          description='主机分页列表（按权限过滤）'),
    route('/server/host/list_page', ServerList, 'server_list_page',
          description='主机分页列表（前端表格用）'),
    route('/server/group_list', GroupList, 'server_list',
          description='按组聚合的主机列表'),
    route('/server/host_list_cmd', ServerListCmd, 'sh_list_cmd',
          roles=['admin', 'user'],
          description='多主机批量命令结果列表'),
    route('/server/file/put', ServerScript, 'sh_script',
          is_property=False,
          description='下发 Shell 脚本到远程主机执行（远端脚本，与 /local/file/put 写本地 data 区分，REV38-M12）'),
    route('/server/group/cmd', GroupCmd, 'sh_cmd',
          is_property=False,
          description='对主机组批量执行 SSH 命令'),
]
